### PR TITLE
Add inverse

### PR DESCRIPTION
**Pull request by bucko909**
This should make the operators in the filters panel clickable; clicking them should invert them.

### CODE REVIEW

**Comment by dvarrazzo** [comment]
Hey hello!

This changeset doesn't seem to change [the json interface](https://github.com/GambitResearch/bacon/blob/master/bacon/observers/json.py), only the django interface. I wonder if it makes sense to extend the changeset to json too?

In my view the Django interface is in a direction of obsolescence, as is server-generated html...

**Comment by bucko909** [comment]
@dvarrazzo So, from a scan through the code I suppose I'd be wanting to add thinks into the `links` dictionaries of the various parts generated by that file? How do those URLs end up in the JS-rendered document? (eg. I can only see hits for `drop_axis` in `json.py`, but I'd expect something to be reading those URLs back out again and injecting them into the formatted document in the right place.) Is this something implemented by the implementing application?

**Comment by bucko909** [comment]
@dvarrazzo I _think_ that's all that's required to close your comment. I'm moderately sure after a bit of looking that we no longer have any code using the non-obsolescence-headed version! (The DHTML-enabled stuff all fetches the HTML from the server.)

**Comment by bucko909** [comment]
Rebased and squashed.

**Pull request merged**
